import type { KnowledgeArticle, KnowledgeIndex, SnippetFile } from "./types";

// Generated by scripts/import-knowledge.ts — run `npm run import-knowledge`
import indexData from "./generated/index.json";
import snippetsData from "./generated/snippets.json";

export const knowledgeIndex = indexData as KnowledgeIndex;
export const knowledgeSnippets = snippetsData as SnippetFile[];

export function getArticleByRoute(route: string): KnowledgeArticle | undefined {
  return knowledgeIndex.articles.find((a) => a.route === route);
}

export function getArticleBySlug(slug: string): KnowledgeArticle | undefined {
  return knowledgeIndex.articles.find((a) => a.slug === slug);
}

export function getArticleById(id: string): KnowledgeArticle | undefined {
  return knowledgeIndex.articles.find((a) => a.id === id);
}

export function getArticlesByCategory(category: KnowledgeArticle["category"]) {
  return knowledgeIndex.articles.filter((a) => a.category === category && !a.slug.toLowerCase().endsWith("readme"));
}

export function getCompanyArticles() {
  return knowledgeIndex.companies;
}

export function searchKnowledge(query: string, limit = 20) {
  const q = query.toLowerCase().trim();
  if (!q) return [];
  return knowledgeIndex.searchIndex
    .filter((item) => {
      const hay = `${item.title} ${item.summary} ${item.contentPreview} ${item.tags.join(" ")} ${item.company ?? ""}`.toLowerCase();
      return hay.includes(q);
    })
    .slice(0, limit);
}

export function getAdjacentArticles(route: string) {
  const catArticles = knowledgeIndex.articles
    .filter((a) => a.category === getArticleByRoute(route)?.category)
    .sort((a, b) => a.title.localeCompare(b.title));
  const idx = catArticles.findIndex((a) => a.route === route);
  return {
    prev: idx > 0 ? catArticles[idx - 1] : null,
    next: idx < catArticles.length - 1 ? catArticles[idx + 1] : null,
  };
}

export function getAllRoutes() {
  return knowledgeIndex.articles.map((a) => a.route);
}

export function getImportStats() {
  return knowledgeIndex.stats;
}
