import type { Release, UpcomingRelease } from "./types";

const GITHUB = "https://github.com/kazinayeem/assignment-pdf-generator";

export const CHANGELOG_RELEASES: Release[] = [
  {
    id: "v6-1",
    version: "v6.1",
    semver: "6.1.0",
    date: "2026-06-28",
    releaseType: "minor",
    status: "released",
    products: ["bornoflow", "bornomaps"],
    title: "BornoMaps Graph V2 & Changelog Center",
    overview:
      "Interactive roadmap graph redesign, premium navbar refactor, BornoFlow rebranding, and a professional release management center.",
    githubUrl: `${GITHUB}/releases/tag/v6.1.0`,
    docsUrl: "/roadmaps",
    stats: { commits: 186, linesChanged: 12400, contributors: 2, roadmapsAdded: 12, devToolsAdded: 0, universitiesAdded: 0, interviewQuestionsAdded: 0, learningTopicsAdded: 0 },
    changes: [
      { id: "v61-1", title: "Interactive Roadmap Graph V2 with zoom, pan, and minimap", category: "bornomaps", product: "bornomaps", tags: ["new", "popular"] },
      { id: "v61-2", title: "75+ career roadmaps with interview questions and coding problems", category: "bornomaps", product: "bornomaps", tags: ["new"] },
      { id: "v61-3", title: "Roadmap readiness score and PDF export", category: "bornomaps", product: "bornomaps", tags: ["new"] },
      { id: "v61-4", title: "Premium SaaS navbar with mega menus and ⌘K search", category: "ui", product: "bornoflow", tags: ["improved"] },
      { id: "v61-5", title: "BornoFlow / Bornosoft rebranding across platform", category: "feature", product: "bornoflow", tags: ["new"] },
      { id: "v61-6", title: "Professional About page with founder profiles", category: "feature", product: "bornoflow", tags: ["new"] },
      { id: "v61-7", title: "Premium multi-column footer redesign", category: "ui", product: "bornoflow", tags: ["improved"] },
      { id: "v61-8", title: "THE Sustainability rankings for Bangladesh universities", category: "university", product: "bornouni", tags: ["new"] },
      { id: "v61-9", title: "Graph rendering performance optimizations", category: "performance", product: "bornomaps", tags: ["performance"] },
      { id: "v61-10", title: "Fixed navbar contrast on light hero sections", category: "bugfix", product: "bornoflow", tags: ["fixed"] },
      { id: "v61-11", title: "Bangla translations for roadmaps and about sections", category: "i18n", product: "bornoflow", tags: ["improved"] },
      { id: "v61-12", title: "Professional Changelog & Release Notes center", category: "feature", product: "bornoflow", tags: ["new", "popular"] },
    ],
    developerNotes: ["Roadmap store key remains campusflow-roadmaps-v1 for backward compatibility.", "Graph V2 uses React Flow with custom node components."],
  },
  {
    id: "v6-0",
    version: "v6.0",
    semver: "6.0.0",
    date: "2026-06-15",
    releaseType: "major",
    status: "released",
    products: ["bornomaps", "bornoflow"],
    title: "BornoMaps Launch",
    overview: "Major release introducing BornoMaps — interactive career roadmaps with 75+ learning paths, graph visualization, and career readiness tools.",
    githubUrl: `${GITHUB}/releases/tag/v6.0.0`,
    docsUrl: "/roadmaps",
    stats: { commits: 240, linesChanged: 18200, contributors: 2, roadmapsAdded: 75, devToolsAdded: 0, universitiesAdded: 0, interviewQuestionsAdded: 162, learningTopicsAdded: 0 },
    changes: [
      { id: "v60-1", title: "BornoMaps module with 75+ interactive career roadmaps", category: "bornomaps", product: "bornomaps", tags: ["new", "popular"] },
      { id: "v60-2", title: "Roadmap graph visualization and node detail panels", category: "bornomaps", product: "bornomaps", tags: ["new"] },
      { id: "v60-3", title: "Career readiness scoring per roadmap", category: "bornomaps", product: "bornomaps", tags: ["new"] },
      { id: "v60-4", title: "162+ interview questions per roadmap topic", category: "bornomaps", product: "bornomaps", tags: ["new"] },
      { id: "v60-5", title: "37 coding problems with solutions per roadmap", category: "bornomaps", product: "bornomaps", tags: ["new"] },
      { id: "v60-6", title: "Portfolio checklist and learning path bar", category: "bornomaps", product: "bornomaps", tags: ["new"] },
      { id: "v60-7", title: "Roadmap dashboard with progress tracking", category: "bornomaps", product: "bornomaps", tags: ["new"] },
      { id: "v60-8", title: "Roadmap PDF export with branding", category: "bornomaps", product: "bornomaps", tags: ["new"] },
      { id: "v60-9", title: "Search and filter roadmaps by category", category: "improvement", product: "bornomaps", tags: ["improved"] },
      { id: "v60-10", title: "Lazy-loaded roadmap catalog for faster initial load", category: "performance", product: "bornomaps", tags: ["performance"] },
    ],
    breakingChanges: ["Roadmaps moved from /career/roadmaps to dedicated /roadmaps module."],
    migrationGuide: ["Use /roadmaps instead of /career/roadmaps for the new BornoMaps experience."],
  },
  {
    id: "v5-1",
    version: "v5.1",
    semver: "5.1.0",
    date: "2026-05-28",
    releaseType: "patch",
    status: "released",
    products: ["bornoflow"],
    title: "Stability & Performance Patch",
    overview: "Bug fixes, security patches, and performance improvements across the platform.",
    githubUrl: `${GITHUB}/releases/tag/v5.1.0`,
    stats: { commits: 42, linesChanged: 2100, contributors: 2 },
    changes: [
      { id: "v51-1", title: "Security headers and CSP improvements", category: "security", product: "bornoflow", tags: ["security"] },
      { id: "v51-2", title: "Optimized animation performance on low-end devices", category: "performance", product: "bornoflow", tags: ["performance"] },
      { id: "v51-3", title: "Fixed university search pagination", category: "bugfix", product: "bornouni", tags: ["fixed"] },
      { id: "v51-4", title: "Accessibility improvements for screen readers", category: "accessibility", product: "bornoflow", tags: ["improved"] },
    ],
    archived: false,
  },
  {
    id: "v5-0",
    version: "v5.0",
    semver: "5.0.0",
    date: "2026-05-20",
    releaseType: "major",
    status: "released",
    products: ["university", "bornouni", "bornoflow"],
    title: "University Hub",
    overview: "Complete University Hub with 180+ Bangladesh universities, rankings, tuition calculator, department explorer, and comparison tools.",
    githubUrl: `${GITHUB}/releases/tag/v5.0.0`,
    docsUrl: "/universities",
    stats: { commits: 198, linesChanged: 15600, contributors: 2, roadmapsAdded: 0, devToolsAdded: 0, universitiesAdded: 180, interviewQuestionsAdded: 0, learningTopicsAdded: 0 },
    changes: [
      { id: "v50-1", title: "University Hub with 180+ Bangladesh universities", category: "university", product: "university", tags: ["new", "popular"] },
      { id: "v50-2", title: "QS World and THE sustainability rankings", category: "university", product: "bornouni", tags: ["new"] },
      { id: "v50-3", title: "Tuition calculator and department details", category: "university", product: "bornouni", tags: ["new"] },
      { id: "v50-4", title: "University comparison and PDF export", category: "university", product: "bornouni", tags: ["new"] },
      { id: "v50-5", title: "Admission predictor and scholarship finder", category: "university", product: "bornouni", tags: ["new"] },
      { id: "v50-6", title: "Landing V5 audit with expanded FAQ", category: "feature", product: "bornoflow", tags: ["improved"] },
      { id: "v50-7", title: "University trust section on landing page", category: "ui", product: "bornoflow", tags: ["new"] },
      { id: "v50-8", title: "Product demo section", category: "feature", product: "bornoflow", tags: ["new"] },
      { id: "v50-9", title: "Theme flicker fixes on page load", category: "bugfix", product: "bornoflow", tags: ["fixed"] },
      { id: "v50-10", title: "Mobile navigation improvements", category: "mobile", product: "bornoflow", tags: ["improved"] },
      { id: "v50-11", title: "Lazy-loaded landing sections", category: "performance", product: "bornoflow", tags: ["performance"] },
    ],
  },
  {
    id: "v4-0",
    version: "v4.0",
    semver: "4.0.0",
    date: "2026-04-10",
    releaseType: "major",
    status: "released",
    products: ["interview", "bornocareer", "bornoflow"],
    title: "Interview Hub",
    overview: "Bangladesh tech company interview knowledge base with 789+ questions, flashcards, quizzes, and career hub integration.",
    githubUrl: `${GITHUB}/releases/tag/v4.0.0`,
    docsUrl: "/interview",
    stats: { commits: 156, linesChanged: 11200, contributors: 2, roadmapsAdded: 0, devToolsAdded: 15, universitiesAdded: 0, interviewQuestionsAdded: 789, learningTopicsAdded: 0 },
    changes: [
      { id: "v40-1", title: "Interview Hub with 37+ company question banks", category: "feature", product: "interview", tags: ["new", "popular"] },
      { id: "v40-2", title: "789+ interview questions imported from knowledge base", category: "feature", product: "interview", tags: ["new"] },
      { id: "v40-3", title: "1014 quizzes and 228 flashcards generated", category: "learning", product: "interview", tags: ["new"] },
      { id: "v40-4", title: "Career Hub with job tracker and application management", category: "bornocareer", product: "bornocareer", tags: ["new"] },
      { id: "v40-5", title: "Bangla i18n support across platform", category: "i18n", product: "bornoflow", tags: ["new"] },
      { id: "v40-6", title: "DevTools expansion with 15 new utilities", category: "bornodev", product: "devtools", tags: ["new"] },
      { id: "v40-7", title: "Dark mode contrast improvements", category: "ui", product: "bornoflow", tags: ["improved"] },
      { id: "v40-8", title: "PDF export edge case fixes", category: "bugfix", product: "bornoflow", tags: ["fixed"] },
      { id: "v40-9", title: "Build-time knowledge import pipeline", category: "dx", product: "bornoflow", tags: ["improved"] },
      { id: "v40-10", title: "Code splitting for faster route loads", category: "performance", product: "bornoflow", tags: ["performance"] },
    ],
  },
  {
    id: "v3-0",
    version: "v3.0",
    semver: "3.0.0",
    date: "2026-03-05",
    releaseType: "major",
    status: "released",
    products: ["resume", "bornocareer"],
    title: "Resume Builder",
    overview: "ATS-friendly resume builder with templates, real-time preview, PDF export, and ATS score checker.",
    githubUrl: `${GITHUB}/releases/tag/v3.0.0`,
    docsUrl: "/cv-builder",
    stats: { commits: 124, linesChanged: 8900, contributors: 2, roadmapsAdded: 0, devToolsAdded: 0, universitiesAdded: 0, interviewQuestionsAdded: 0, learningTopicsAdded: 0 },
    changes: [
      { id: "v30-1", title: "ATS Resume Builder with multiple templates", category: "resume", product: "resume", tags: ["new", "popular"] },
      { id: "v30-2", title: "Real-time preview and PDF export", category: "resume", product: "resume", tags: ["new"] },
      { id: "v30-3", title: "ATS score checker with keyword analysis", category: "bornocareer", product: "bornocareer", tags: ["new"] },
      { id: "v30-4", title: "Cover letter generator integration", category: "bornocareer", product: "bornocareer", tags: ["new"] },
      { id: "v30-5", title: "Resume section drag-and-drop reordering", category: "improvement", product: "resume", tags: ["improved"] },
      { id: "v30-6", title: "Print-optimized resume layout", category: "desktop", product: "resume", tags: ["new"] },
      { id: "v30-7", title: "Fixed PDF font rendering on mobile", category: "bugfix", product: "resume", tags: ["fixed"] },
    ],
  },
  {
    id: "v2-0",
    version: "v2.0",
    semver: "2.0.0",
    date: "2026-02-01",
    releaseType: "major",
    status: "released",
    products: ["devtools", "bornodev"],
    title: "Developer Tools",
    overview: "100+ developer utilities including JSON/YAML formatters, encoders, generators, CSS tools, and code playgrounds.",
    githubUrl: `${GITHUB}/releases/tag/v2.0.0`,
    docsUrl: "/developer-tools",
    stats: { commits: 178, linesChanged: 14200, contributors: 2, roadmapsAdded: 0, devToolsAdded: 100, universitiesAdded: 0, interviewQuestionsAdded: 0, learningTopicsAdded: 0 },
    changes: [
      { id: "v20-1", title: "BornoDev toolbox with 100+ utilities", category: "bornodev", product: "devtools", tags: ["new", "popular"] },
      { id: "v20-2", title: "JSON, YAML, XML formatters and validators", category: "bornodev", product: "devtools", tags: ["new"] },
      { id: "v20-3", title: "Base64, URL, and hash encoders", category: "bornodev", product: "devtools", tags: ["new"] },
      { id: "v20-4", title: "UUID, password, and QR code generators", category: "bornodev", product: "devtools", tags: ["new"] },
      { id: "v20-5", title: "CSS gradient and shadow generators", category: "bornodev", product: "devtools", tags: ["new"] },
      { id: "v20-6", title: "Color picker and converter tools", category: "bornodev", product: "devtools", tags: ["new"] },
      { id: "v20-7", title: "Regex tester and diff viewer", category: "bornodev", product: "devtools", tags: ["new"] },
      { id: "v20-8", title: "Keyboard shortcuts for power users", category: "dx", product: "devtools", tags: ["improved"] },
      { id: "v20-9", title: "Tool search and category filtering", category: "improvement", product: "devtools", tags: ["improved"] },
    ],
  },
  {
    id: "v1-0",
    version: "v1.0",
    semver: "1.0.0",
    date: "2026-01-10",
    releaseType: "major",
    status: "released",
    products: ["bornoflow", "assignment", "labreport", "learning"],
    title: "Platform Launch",
    overview: "Initial BornoFlow launch with assignment covers, lab reports, CS learning modules, and academic productivity tools.",
    githubUrl: `${GITHUB}/releases/tag/v1.0.0`,
    docsUrl: "/about",
    stats: { commits: 320, linesChanged: 28000, contributors: 2, roadmapsAdded: 0, devToolsAdded: 0, universitiesAdded: 0, interviewQuestionsAdded: 0, learningTopicsAdded: 45 },
    changes: [
      { id: "v10-1", title: "BornoFlow platform launch", category: "feature", product: "bornoflow", tags: ["new", "popular"] },
      { id: "v10-2", title: "Assignment Cover Generator for DIU format", category: "assignment", product: "assignment", tags: ["new"] },
      { id: "v10-3", title: "Lab Report Generator with PDF export", category: "labreport", product: "labreport", tags: ["new"] },
      { id: "v10-4", title: "CS Learning modules with 45+ topics", category: "learning", product: "learning", tags: ["new"] },
      { id: "v10-5", title: "Interactive quizzes and progress tracking", category: "learning", product: "learning", tags: ["new"] },
      { id: "v10-6", title: "Firebase authentication and student portal", category: "infrastructure", product: "bornoflow", tags: ["new"] },
      { id: "v10-7", title: "Dark mode and responsive design", category: "ui", product: "bornoflow", tags: ["new"] },
      { id: "v10-8", title: "PWA support with offline capabilities", category: "mobile", product: "bornoflow", tags: ["new"] },
      { id: "v10-9", title: "Vercel deployment with edge middleware", category: "infrastructure", product: "bornoflow", tags: ["new"] },
    ],
    developerNotes: ["Initial release branded as CampusFlow, later rebranded to BornoFlow in v6.1."],
    archived: true,
  },
];

export const UPCOMING_RELEASES: UpcomingRelease[] = [
  { id: "u1", title: "Borno AI Learning Assistant", status: "inDevelopment", progress: 65, quarter: "Q3 2026", product: "bornoai" },
  { id: "u2", title: "AI Interview Coach", status: "comingSoon", progress: 80, quarter: "Q3 2026", product: "interview" },
  { id: "u3", title: "Mobile PWA V2", status: "planned", progress: 30, quarter: "Q3 2026", product: "bornoflow" },
  { id: "u4", title: "University Partnerships Portal", status: "planned", progress: 15, quarter: "Q4 2026", product: "bornouni" },
  { id: "u5", title: "BornoMaps Playground", status: "research", progress: 10, quarter: "Q4 2026", product: "bornomaps" },
  { id: "u6", title: "News Hub & Content Platform", status: "ideas", progress: 5, quarter: "2027", product: "bornoflow" },
];

export const CURRENT_VERSION = CHANGELOG_RELEASES[0];

export function getReleaseById(id: string): Release | undefined {
  return CHANGELOG_RELEASES.find((r) => r.id === id);
}

export function getReleaseByVersion(version: string): Release | undefined {
  return CHANGELOG_RELEASES.find((r) => r.version === version);
}
