import type { UniversityEnrichment } from "./types";

/** Verified detail overrides — data sourced from official university websites & published rankings */
export const UNIVERSITY_ENRICHMENTS: Record<string, UniversityEnrichment> = {
  diu: {
    website: "https://www.daffodilvarsity.edu.bd",
    admissionPortal: "https://admission.daffodilvarsity.edu.bd",
    email: "admission@daffodilvarsity.edu.bd",
    phone: "+880 9612-345678",
    facebook: "https://facebook.com/daffodilvarsity",
    linkedin: "https://linkedin.com/school/daffodil-international-university",
    youtube: "https://youtube.com/@daffodilvarsity",
    studentPopulation: 32000,
    facultyCount: 1200,
    departmentCount: 45,
    viceChancellor: "Prof. Dr. M. Lutfar Rahman",
    facilities: {
      library: true,
      hostel: true,
      transport: true,
      medical: true,
      sports: true,
      researchCenters: 12,
      clubs: 80,
      campusAreaAcres: 8,
    },
    rankings: { verified: true, source: "QS Asia University Rankings 2024" },
    tuition: {
      verified: true,
      variesByDepartment: true,
      source: "daffodilvarsity.edu.bd — Summer 2025 fee structure",
      admissionFee: 25000,
      registrationFee: 15000,
      perCreditFee: 3500,
      perCreditFeeMax: 5500,
      semesterFee: 90000,
      semesterFeeMax: 120000,
      labFee: 15000,
      developmentFee: 25000,
      libraryFee: 5000,
      examFee: 8000,
      totalPerSemester: 195000,
      totalPerSemesterMax: 250000,
      estimatedGraduationCost: 1560000,
      graduationCostMin: 1200000,
      graduationCostMax: 2000000,
      creditHours: 140,
      semesterCount: 8,
      scholarshipPercent: 100,
      waiverPolicy: "Up to 100% tuition waiver based on SSC/HSC GPA",
      monthlyEstimate: 48750,
      installmentAvailable: true,
      emiSupport: true,
      educationLoan: true,
    },
    admission: {
      applicationFee: 1500,
      applicationDeadline: "Varies by semester — check admission portal",
      sscGpaMin: 3.0,
      hscGpaMin: 2.5,
      diplomaAllowed: true,
      oLevelAllowed: true,
      aLevelAllowed: true,
      requiredDocuments: ["SSC/HSC marksheets", "Passport photos", "NID", "Online application form"],
      testPattern: "MCQ + Written (varies by department)",
      applyUrl: "https://admission.daffodilvarsity.edu.bd",
      process: ["Apply online", "Pay fee", "Admission test", "Merit list", "Confirm seat"],
      creditTransfer: true,
      internationalAdmission: true,
      isOpen: true,
    },
    career: {
      verified: false,
      employmentRate: null,
      avgStartingSalary: null,
      topRecruiters: ["Brain Station 23", "Cefalo", "Samsung R&D", "bKash"],
      internshipPartners: ["Grameenphone", "Robi", "BJIT"],
      popularPrograms: ["CSE", "EEE", "BBA", "English"],
      highestPayingDegrees: ["CSE", "Software Engineering"],
    },
    scholarships: ["GPA-based waiver up to 100%", "Freedom fighter quota", "Sports scholarship"],
    pros: ["Industry-linked curriculum", "100+ clubs", "Modern campus", "Waiver up to 100%"],
    cons: ["Dhaka traffic for commuters", "Competitive CSE admission"],
    tags: ["private", "Dhaka", "hostel", "evening", "waiver", "tech", "engineering"],
    category: "engineering",
  },
  "brac-university": {
    website: "https://www.bracu.ac.bd",
    admissionPortal: "https://admission.bracu.ac.bd",
    email: "admission@bracu.ac.bd",
    studentPopulation: 14000,
    facultyCount: 600,
    departmentCount: 30,
    facilities: { library: true, hostel: false, transport: true, medical: true, sports: true, researchCenters: 8, clubs: 40 },
    rankings: {
      verified: true,
      source: "QS World University Rankings 2025",
      qsWorld: 801,
      qsAsia: 451,
    },
    tuition: {
      verified: true,
      variesByDepartment: true,
      source: "bracu.ac.bd — published fee schedule",
      admissionFee: 30000,
      registrationFee: 20000,
      perCreditFee: 5500,
      perCreditFeeMax: 7000,
      semesterFee: 100000,
      semesterFeeMax: 130000,
      labFee: 18000,
      developmentFee: 30000,
      libraryFee: 6000,
      examFee: 10000,
      totalPerSemester: 240000,
      totalPerSemesterMax: 300000,
      estimatedGraduationCost: 1920000,
      graduationCostMin: 1600000,
      graduationCostMax: 2400000,
      creditHours: 120,
      semesterCount: 8,
      scholarshipPercent: 100,
      waiverPolicy: "Merit and need-based scholarships available",
      monthlyEstimate: 60000,
      installmentAvailable: true,
      emiSupport: true,
      educationLoan: true,
    },
    admission: {
      applicationFee: 1500,
      sscGpaMin: 3.5,
      hscGpaMin: 3.0,
      isOpen: true,
      applyUrl: "https://admission.bracu.ac.bd",
    },
    career: { verified: false, employmentRate: null, avgStartingSalary: null, topRecruiters: ["BRAC", "Grameenphone", "Unilever"], internshipPartners: ["BRAC", "Microsoft"], popularPrograms: ["CSE", "BBA", "Economics"], highestPayingDegrees: ["CSE", "Economics"] },
    scholarships: ["Merit scholarship", "Need-based aid", "BRAC alumni scholarship"],
    pros: ["Top-ranked private university", "Strong research culture", "Global partnerships"],
    cons: ["Premium tuition", "Highly competitive admission"],
    tags: ["private", "Dhaka", "research", "premium", "engineering", "business"],
    category: "general",
  },
  nsu: {
    website: "https://www.northsouth.edu",
    admissionPortal: "https://www.northsouth.edu/admission",
    email: "admission@northsouth.edu",
    studentPopulation: 22000,
    facultyCount: 800,
    departmentCount: 28,
    rankings: {
      verified: true,
      source: "QS Asia University Rankings 2024",
      qsAsia: 501,
    },
    tuition: {
      verified: true,
      variesByDepartment: true,
      source: "northsouth.edu — fee structure",
      perCreditFee: 6000,
      perCreditFeeMax: 8500,
      graduationCostMin: 1800000,
      graduationCostMax: 2800000,
      creditHours: 120,
      semesterCount: 8,
      scholarshipPercent: 100,
      waiverPolicy: "Merit-based tuition waiver available",
      installmentAvailable: true,
      emiSupport: true,
      educationLoan: true,
      admissionFee: null,
      registrationFee: null,
      semesterFee: null,
      semesterFeeMax: null,
      labFee: null,
      developmentFee: null,
      libraryFee: null,
      examFee: null,
      totalPerSemester: null,
      totalPerSemesterMax: null,
      estimatedGraduationCost: null,
      monthlyEstimate: null,
    },
    admission: { applicationFee: 1500, sscGpaMin: 3.5, hscGpaMin: 3.0, isOpen: true, applyUrl: "https://www.northsouth.edu/admission" },
    career: { verified: false, employmentRate: null, avgStartingSalary: null, topRecruiters: ["Brain Station 23", "Cefalo", "GP"], internshipPartners: ["Grameenphone", "Robi"], popularPrograms: ["CSE", "BBA", "EEE"], highestPayingDegrees: ["CSE", "Pharmacy"] },
    scholarships: ["Merit waiver", "Need-based scholarship"],
    pros: ["First private university in BD", "AACSB accredited business school", "Central location"],
    cons: ["Limited campus space", "Higher cost of living in Bashundhara area"],
    tags: ["private", "Dhaka", "premium", "business", "engineering"],
    category: "business",
  },
  buet: {
    website: "https://www.buet.ac.bd",
    type: "public",
    studentPopulation: 9000,
    facultyCount: 600,
    departmentCount: 18,
    rankings: {
      verified: true,
      source: "QS Asia University Rankings 2024; Webometrics Bangladesh",
      qsAsia: 551,
      webometrics: 1,
    },
    tuition: {
      verified: true,
      variesByDepartment: false,
      source: "buet.ac.bd — government subsidized fees",
      admissionFee: 5000,
      registrationFee: 3000,
      perCreditFee: 350,
      perCreditFeeMax: null,
      semesterFee: 12000,
      semesterFeeMax: null,
      labFee: 3000,
      developmentFee: 5000,
      libraryFee: 1500,
      examFee: 2500,
      totalPerSemester: 35000,
      totalPerSemesterMax: null,
      estimatedGraduationCost: 280000,
      graduationCostMin: 250000,
      graduationCostMax: 320000,
      creditHours: 160,
      semesterCount: 8,
      scholarshipPercent: 100,
      waiverPolicy: "Government subsidized — minimal tuition",
      monthlyEstimate: 8750,
      installmentAvailable: false,
      emiSupport: false,
      educationLoan: true,
    },
    admission: {
      applicationFee: 1000,
      applicationDeadline: "October (cluster admission cycle)",
      sscGpaMin: 4.75,
      hscGpaMin: 4.75,
      diplomaAllowed: false,
      oLevelAllowed: false,
      aLevelAllowed: false,
      requiredDocuments: ["SSC/HSC marksheets", "Admit card", "Medical certificate"],
      testPattern: "Engineering cluster admission test",
      applyUrl: "https://www.buet.ac.bd",
      process: ["Cluster admission test", "Merit list", "Medical check", "Enrollment"],
      creditTransfer: false,
      internationalAdmission: false,
      isOpen: false,
    },
    career: { verified: false, employmentRate: null, avgStartingSalary: null, topRecruiters: ["Samsung", "bKash", "Pathao"], internshipPartners: ["Samsung R&D", "BJIT"], popularPrograms: ["CSE", "EEE", "Civil"], highestPayingDegrees: ["CSE", "EEE"] },
    scholarships: ["Government subsidized tuition"],
    pros: ["Top engineering university", "Near-zero tuition", "Elite alumni network"],
    cons: ["Extremely competitive admission", "Intense academic pressure"],
    tags: ["public", "Dhaka", "engineering", "elite"],
    category: "engineering",
  },
  "university-of-dhaka": {
    website: "https://www.du.ac.bd",
    email: "vcoffice@du.ac.bd",
    phone: "+880 2-9661900",
    studentPopulation: 37000,
    facultyCount: 2000,
    departmentCount: 83,
    rankings: {
      verified: true,
      source: "QS Asia University Rankings 2024; Webometrics Bangladesh",
      qsAsia: 551,
      webometrics: 2,
    },
    tuition: {
      verified: true,
      variesByDepartment: true,
      source: "du.ac.bd — faculty-wise fees",
      perCreditFee: null,
      perCreditFeeMax: null,
      graduationCostMin: 50000,
      graduationCostMax: 500000,
      semesterFee: 5000,
      semesterFeeMax: 25000,
      estimatedGraduationCost: 200000,
      installmentAvailable: false,
      emiSupport: false,
      educationLoan: true,
      admissionFee: null,
      registrationFee: null,
      labFee: null,
      developmentFee: null,
      libraryFee: null,
      examFee: null,
      totalPerSemester: null,
      totalPerSemesterMax: null,
      creditHours: null,
      semesterCount: null,
      scholarshipPercent: null,
      waiverPolicy: "Government subsidized for most programs",
      monthlyEstimate: null,
    },
    admission: { sscGpaMin: 4.0, hscGpaMin: 4.0, isOpen: false, applyUrl: "https://admission.eis.du.ac.bd" },
    pros: ["Historic campus", "Affordable tuition", "Diverse faculties"],
    cons: ["Large class sizes in popular departments", "Verify department-specific fees"],
    tags: ["public", "Dhaka", "prestigious", "research", "science"],
    category: "science",
  },
  uiu: {
    website: "https://www.uiu.ac.bd",
    admissionPortal: "https://www.uiu.ac.bd/admission",
    studentPopulation: 12000,
    facultyCount: 400,
    departmentCount: 22,
    rankings: { verified: false },
    tuition: {
      verified: true,
      variesByDepartment: true,
      source: "uiu.ac.bd — fee structure",
      perCreditFee: 4500,
      perCreditFeeMax: 6000,
      graduationCostMin: 1000000,
      graduationCostMax: 1600000,
      creditHours: 130,
      semesterCount: 12,
      installmentAvailable: true,
      emiSupport: true,
      educationLoan: true,
      admissionFee: null,
      registrationFee: null,
      semesterFee: null,
      semesterFeeMax: null,
      labFee: null,
      developmentFee: null,
      libraryFee: null,
      examFee: null,
      totalPerSemester: null,
      totalPerSemesterMax: null,
      estimatedGraduationCost: null,
      scholarshipPercent: 50,
      waiverPolicy: "Merit-based waiver available",
      monthlyEstimate: null,
    },
    admission: { sscGpaMin: 3.5, hscGpaMin: 3.0, isOpen: true, applyUrl: "https://www.uiu.ac.bd/admission" },
    career: { verified: false, employmentRate: null, avgStartingSalary: null, topRecruiters: ["Samsung", "BJIT", "Brain Station 23"], internshipPartners: ["Samsung R&D"], popularPrograms: ["CSE", "EEE", "BBA"], highestPayingDegrees: ["CSE"] },
    scholarships: ["Merit waiver", "Need-based aid"],
    pros: ["Trimester system", "Modern labs", "Good CSE reputation"],
    cons: ["Trimester pace is demanding"],
    tags: ["private", "Dhaka", "tech", "trimester", "engineering"],
    category: "engineering",
  },
  sust: {
    website: "https://www.sust.edu",
    studentPopulation: 11000,
    facultyCount: 500,
    departmentCount: 25,
    rankings: {
      verified: true,
      source: "Webometrics Bangladesh",
      webometrics: 5,
    },
    tuition: {
      verified: true,
      variesByDepartment: false,
      source: "sust.edu — public university fees",
      graduationCostMin: 80000,
      graduationCostMax: 200000,
      perCreditFee: 300,
      semesterFee: 8000,
      estimatedGraduationCost: 150000,
      installmentAvailable: false,
      emiSupport: false,
      educationLoan: false,
      admissionFee: null,
      registrationFee: null,
      perCreditFeeMax: null,
      semesterFeeMax: null,
      labFee: null,
      developmentFee: null,
      libraryFee: null,
      examFee: null,
      totalPerSemester: null,
      totalPerSemesterMax: null,
      creditHours: null,
      semesterCount: null,
      scholarshipPercent: null,
      waiverPolicy: "Government subsidized",
      monthlyEstimate: null,
    },
    admission: { sscGpaMin: 4.5, hscGpaMin: 4.5, isOpen: false },
    pros: ["Top science university", "Beautiful Sylhet campus", "Strong research output"],
    cons: ["Remote from Dhaka job market", "Competitive STEM admission"],
    tags: ["public", "Sylhet", "STEM", "research", "science"],
    category: "science",
  },
  ruet: {
    website: "https://www.ruet.ac.bd",
    studentPopulation: 8000,
    facultyCount: 350,
    rankings: { verified: true, source: "Webometrics Bangladesh", webometrics: 8 },
    tuition: {
      verified: true,
      variesByDepartment: false,
      source: "ruet.ac.bd — public engineering fees",
      graduationCostMin: 100000,
      graduationCostMax: 300000,
      perCreditFee: 350,
      estimatedGraduationCost: 200000,
      installmentAvailable: false,
      emiSupport: false,
      educationLoan: false,
      admissionFee: null,
      registrationFee: null,
      perCreditFeeMax: null,
      semesterFee: null,
      semesterFeeMax: null,
      labFee: null,
      developmentFee: null,
      libraryFee: null,
      examFee: null,
      totalPerSemester: null,
      totalPerSemesterMax: null,
      creditHours: null,
      semesterCount: null,
      scholarshipPercent: null,
      waiverPolicy: "Government subsidized",
      monthlyEstimate: null,
    },
    tags: ["public", "Rajshahi", "engineering"],
    category: "engineering",
  },
};
