import type { University } from "./types";

/** Rich detail overrides for flagship universities */
export const UNIVERSITY_ENRICHMENTS: Record<string, Partial<University>> = {
  diu: {
    website: "https://www.daffodilvarsity.edu.bd",
    admissionPortal: "https://admission.daffodilvarsity.edu.bd",
    email: "admission@daffodilvarsity.edu.bd",
    phone: "+880 9612-345678",
    facebook: "https://facebook.com/daffodilvarsity",
    linkedin: "https://linkedin.com/school/daffodil-international-university",
    youtube: "https://youtube.com/@daffodilvarsity",
    studentPopulation: 32000,
    facultyCount: 1200,
    departmentCount: 45,
    viceChancellor: "Prof. Dr. M. Lutfar Rahman",
    facilities: {
      library: true,
      hostel: true,
      transport: true,
      medical: true,
      sports: true,
      researchCenters: 12,
      clubs: 80,
      campusAreaAcres: 8,
    },
    rankings: { national: 15, employability: 88, research: 72 },
    tuition: {
      admissionFee: 25000,
      registrationFee: 15000,
      perCreditFee: 4500,
      semesterFee: 90000,
      labFee: 15000,
      developmentFee: 25000,
      libraryFee: 5000,
      examFee: 8000,
      totalPerSemester: 195000,
      estimatedGraduationCost: 1560000,
      scholarshipPercent: 100,
      waiverPolicy: "Up to 100% tuition waiver based on SSC/HSC GPA (5.00 = 50%, 4.80+ = 40%)",
      monthlyEstimate: 48750,
      installmentAvailable: true,
      emiSupport: true,
      educationLoan: true,
    },
    admission: {
      applicationFee: 1500,
      applicationDeadline: "August 15",
      sscGpaMin: 3.0,
      hscGpaMin: 2.5,
      diplomaAllowed: true,
      oLevelAllowed: true,
      aLevelAllowed: true,
      requiredDocuments: ["SSC/HSC marksheets", "Passport photos", "NID", "Online application form"],
      testPattern: "MCQ + Written (CSE/EEE/BBA separate)",
      applyUrl: "https://admission.daffodilvarsity.edu.bd",
      process: ["Apply online", "Pay fee", "Admission test", "Merit list", "Confirm seat"],
      creditTransfer: true,
      internationalAdmission: true,
    },
    career: {
      employmentRate: 92,
      avgStartingSalary: 45000,
      topRecruiters: ["Brain Station 23", "Cefalo", "Samsung R&D", "bKash", "Daffodil Software"],
      internshipPartners: ["Grameenphone", "Robi", "BJIT", "SSL Wireless"],
      popularPrograms: ["CSE", "EEE", "BBA", "English"],
      highestPayingDegrees: ["CSE", "Software Engineering", "Pharmacy"],
    },
    pros: ["Industry-linked curriculum", "100+ clubs", "Strong IT placement", "Modern campus", "Waiver up to 100%"],
    cons: ["Dhaka traffic for commuters", "Competitive CSE admission"],
    tags: ["private", "Dhaka", "hostel", "evening", "waiver", "tech"],
  },
  brac: {
    website: "https://www.bracu.ac.bd",
    studentPopulation: 14000,
    departmentCount: 30,
    rankings: { national: 3, qs: 800, employability: 90, research: 85 },
    tuition: {
      admissionFee: 30000,
      registrationFee: 20000,
      perCreditFee: 5500,
      semesterFee: 100000,
      labFee: 18000,
      developmentFee: 30000,
      libraryFee: 6000,
      examFee: 10000,
      totalPerSemester: 240000,
      estimatedGraduationCost: 1920000,
      scholarshipPercent: 100,
      waiverPolicy: "Merit and need-based scholarships available",
      monthlyEstimate: 60000,
      installmentAvailable: true,
      emiSupport: true,
      educationLoan: true,
    },
    career: {
      employmentRate: 94,
      avgStartingSalary: 55000,
      topRecruiters: ["Google", "Microsoft", "Unilever", "BRAC", "Grameenphone"],
      internshipPartners: ["BRAC", "Microsoft", "Samsung"],
      popularPrograms: ["CSE", "BBA", "Economics", "Architecture"],
      highestPayingDegrees: ["CSE", "Economics", "MBA"],
    },
    pros: ["Top-ranked private university", "Strong research culture", "Global partnerships", "Beautiful campus"],
    cons: ["Premium tuition", "Highly competitive admission"],
    tags: ["private", "Dhaka", "research", "premium"],
  },
  nsu: {
    website: "https://www.northsouth.edu",
    studentPopulation: 22000,
    rankings: { national: 2, employability: 89, research: 80 },
    career: {
      employmentRate: 91,
      avgStartingSalary: 50000,
      topRecruiters: ["Brain Station 23", "Cefalo", "GP", "Unilever", "City Bank"],
      internshipPartners: ["Grameenphone", "Robi", "Samsung"],
      popularPrograms: ["CSE", "BBA", "EEE", "Pharmacy"],
      highestPayingDegrees: ["CSE", "Pharmacy", "MBA"],
    },
    pros: ["First private university in BD", "AACSB accredited business school", "Central location"],
    cons: ["Limited campus space", "Higher cost of living in Bashundhara area"],
    tags: ["private", "Dhaka", "premium", "business"],
  },
  buet: {
    website: "https://www.buet.ac.bd",
    type: "public",
    studentPopulation: 9000,
    rankings: { national: 1, employability: 98, research: 95 },
    tuition: {
      admissionFee: 5000,
      registrationFee: 3000,
      perCreditFee: 350,
      semesterFee: 12000,
      labFee: 3000,
      developmentFee: 5000,
      libraryFee: 1500,
      examFee: 2500,
      totalPerSemester: 35000,
      estimatedGraduationCost: 280000,
      scholarshipPercent: 100,
      waiverPolicy: "Government subsidized — minimal tuition",
      monthlyEstimate: 8750,
      installmentAvailable: false,
      emiSupport: false,
      educationLoan: true,
    },
    admission: {
      applicationFee: 1000,
      applicationDeadline: "October 15",
      sscGpaMin: 4.75,
      hscGpaMin: 4.75,
      diplomaAllowed: false,
      oLevelAllowed: false,
      aLevelAllowed: false,
      requiredDocuments: ["SSC/HSC marksheets", "Admit card", "Medical certificate"],
      testPattern: "Engineering cluster admission test (Physics, Chemistry, Math, English)",
      applyUrl: "https://www.buet.ac.bd",
      process: ["Cluster admission test", "Merit list", "Medical check", "Enrollment"],
      creditTransfer: false,
      internationalAdmission: false,
    },
    career: {
      employmentRate: 99,
      avgStartingSalary: 65000,
      topRecruiters: ["Google", "Microsoft", "Samsung", "bKash", "Pathao"],
      internshipPartners: ["Samsung R&D", "BJIT", "Cefalo"],
      popularPrograms: ["CSE", "EEE", "Civil", "Mechanical"],
      highestPayingDegrees: ["CSE", "EEE"],
    },
    pros: ["#1 engineering university", "Near-zero tuition", "Elite alumni network", "Top placements"],
    cons: ["Extremely competitive admission", "Intense academic pressure"],
    tags: ["public", "Dhaka", "engineering", "elite"],
  },
  "university-of-dhaka": {
    website: "https://www.du.ac.bd",
    studentPopulation: 37000,
    rankings: { national: 1, employability: 85, research: 92 },
    pros: ["Oxford of the East", "Historic campus", "Affordable tuition", "Diverse faculties"],
    cons: ["Political activity on campus", "Large class sizes in popular departments"],
    tags: ["public", "Dhaka", "prestigious", "research"],
  },
  uiu: {
    website: "https://www.uiu.ac.bd",
    studentPopulation: 12000,
    rankings: { national: 8, employability: 87 },
    career: {
      employmentRate: 90,
      avgStartingSalary: 48000,
      topRecruiters: ["Samsung", "BJIT", "Brain Station 23", "Kaz Software"],
      internshipPartners: ["Samsung R&D", "GP"],
      popularPrograms: ["CSE", "EEE", "BBA"],
      highestPayingDegrees: ["CSE", "EEE"],
    },
    pros: ["Trimester system", "Modern labs", "Good CSE reputation", "Madani Avenue campus"],
    cons: ["Trimester pace is demanding"],
    tags: ["private", "Dhaka", "tech", "trimester"],
  },
  sust: {
    website: "https://www.sust.edu",
    studentPopulation: 11000,
    rankings: { national: 6, employability: 82, research: 88 },
    pros: ["Top science university", "Beautiful Sylhet campus", "Strong research output"],
    cons: ["Remote from Dhaka job market", "Competitive STEM admission"],
    tags: ["public", "Sylhet", "STEM", "research"],
  },
};
