import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { TuitionCalculationResult, University } from "./types";
import { formatRanking, formatTuitionRange, getQsDisplayRank } from "./format";

const tuitionLabels = {
  unavailable: "Contact university",
  variesByDepartment: "Varies by department",
  startingFrom: "From",
  estimated: "estimated",
};

export function exportUniversityPdf(university: University) {
  const doc = new jsPDF();
  doc.setFontSize(18);
  doc.text(university.name, 14, 20);
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`${university.shortName} · ${university.type} · ${university.city}`, 14, 28);
  doc.setTextColor(0);

  let y = 38;
  const lines = [
    `Established: ${university.established}`,
    `Location: ${university.address}`,
    `Website: ${university.website}`,
    `QS Rank: ${formatRanking(getQsDisplayRank(university.rankings), "Not Ranked")}`,
    `Tuition: ${formatTuitionRange(university.tuition, tuitionLabels)}`,
    `Students: ${university.studentPopulation ?? "N/A"}`,
    `Departments: ${university.departmentCount ?? "N/A"}`,
  ];
  lines.forEach((line) => {
    doc.text(line, 14, y);
    y += 7;
  });

  doc.save(`${university.slug}-campusflow.pdf`);
}

export function exportComparisonPdf(universities: University[]) {
  const doc = new jsPDF({ orientation: universities.length > 2 ? "landscape" : "portrait" });
  doc.setFontSize(16);
  doc.text("University Comparison — CampusFlow", 14, 16);

  autoTable(doc, {
    startY: 24,
    head: [["Feature", ...universities.map((u) => u.shortName)]],
    body: [
      ["Type", ...universities.map((u) => u.type)],
      ["Location", ...universities.map((u) => `${u.city}, ${u.division}`)],
      ["QS Rank", ...universities.map((u) => formatRanking(getQsDisplayRank(u.rankings), "N/A"))],
      ["Tuition", ...universities.map((u) => formatTuitionRange(u.tuition, tuitionLabels))],
      ["Hostel", ...universities.map((u) => (u.facilities.hostel ? "Yes" : "No"))],
      ["Departments", ...universities.map((u) => String(u.departmentCount ?? "N/A"))],
      ["Established", ...universities.map((u) => String(u.established))],
    ],
    styles: { fontSize: 9 },
    headStyles: { fillColor: [109, 93, 246] },
  });

  doc.save("university-comparison-campusflow.pdf");
}

export function exportTuitionPdf(university: University, result: TuitionCalculationResult) {
  const doc = new jsPDF();
  doc.setFontSize(16);
  doc.text(`Cost Estimate — ${university.shortName}`, 14, 20);
  doc.setFontSize(10);

  autoTable(doc, {
    startY: 28,
    head: [["Item", "Amount (৳)"]],
    body: [
      ["Admission Fee", result.admissionFee.toLocaleString()],
      ["Registration Fee", result.registrationFee.toLocaleString()],
      ["Per Credit (total)", result.perCreditTotal.toLocaleString()],
      ["Semester Fees", result.semesterFees.toLocaleString()],
      ["Scholarship Discount", `-${result.scholarshipDiscount.toLocaleString()}`],
      ["Waiver Discount", `-${result.waiverDiscount.toLocaleString()}`],
      ["Academic Total", result.academicTotal.toLocaleString()],
      ["Living Cost", result.livingCost.toLocaleString()],
      ["Hostel", result.hostelCost.toLocaleString()],
      ["Transport", result.transportCost.toLocaleString()],
      ["Food", result.foodCost.toLocaleString()],
      ["GRAND TOTAL", result.grandTotal.toLocaleString()],
      ["Monthly Installment", result.monthlyInstallment.toLocaleString()],
    ],
    foot: [[`Generated by CampusFlow · ${university.website}`, ""]],
    styles: { fontSize: 10 },
    headStyles: { fillColor: [109, 93, 246] },
  });

  doc.save(`${university.slug}-cost-estimate.pdf`);
}

export function exportScholarshipPdf(university: University, offers: { name: string; eligible: boolean; waiverPercent: number | null }[]) {
  const doc = new jsPDF();
  doc.setFontSize(16);
  doc.text(`Scholarship Report — ${university.shortName}`, 14, 20);

  autoTable(doc, {
    startY: 28,
    head: [["Scholarship", "Eligible", "Waiver %"]],
    body: offers.map((o) => [o.name, o.eligible ? "Yes" : "No", o.waiverPercent != null ? `${o.waiverPercent}%` : "N/A"]),
    styles: { fontSize: 10 },
    headStyles: { fillColor: [109, 93, 246] },
  });

  doc.save(`${university.slug}-scholarships.pdf`);
}

export function exportAdmissionPdf(university: University, chance: string, confidence: number) {
  const doc = new jsPDF();
  doc.setFontSize(16);
  doc.text(`Admission Report — ${university.shortName}`, 14, 20);
  doc.setFontSize(11);
  doc.text(`Chance: ${chance.replace("-", " ").toUpperCase()}`, 14, 32);
  doc.text(`Confidence: ${confidence}%`, 14, 40);
  doc.text(`SSC Min: ${university.admission.sscGpaMin ?? "N/A"}`, 14, 52);
  doc.text(`HSC Min: ${university.admission.hscGpaMin ?? "N/A"}`, 14, 60);
  doc.save(`${university.slug}-admission-report.pdf`);
}
