import type { UniversityRanking } from "./types";

/** QS World University Rankings 2027 — Bangladesh (published 18 June 2026). Source: topuniversities.com */
export const QS_RANKINGS_2027_SOURCE =
  "QS World University Rankings 2027 (published 18 June 2026)";

export const QS_WORLD_RANKINGS_2027: Record<string, Partial<UniversityRanking>> = {
  "university-of-dhaka": {
    verified: true,
    source: QS_RANKINGS_2027_SOURCE,
    qsSource: QS_RANKINGS_2027_SOURCE,
    qsYear: 2027,
    qsWorld: 600,
    qsWorldDisplay: "600",
    qsOverallScore: 28.3,
    academicReputation: 28.3,
    citationsPerFaculty: 8,
  },
  buet: {
    verified: true,
    source: QS_RANKINGS_2027_SOURCE,
    qsSource: QS_RANKINGS_2027_SOURCE,
    qsYear: 2027,
    qsWorld: 711,
    qsWorldDisplay: "711-720",
    qsOverallScore: null,
    academicReputation: 19.1,
    citationsPerFaculty: 36.2,
  },
  nsu: {
    verified: true,
    source: QS_RANKINGS_2027_SOURCE,
    qsSource: QS_RANKINGS_2027_SOURCE,
    qsYear: 2027,
    qsWorld: 901,
    qsWorldDisplay: "901-950",
    qsOverallScore: null,
    academicReputation: 15,
    citationsPerFaculty: 8.2,
  },
  "brac-university": {
    verified: true,
    source: QS_RANKINGS_2027_SOURCE,
    qsSource: QS_RANKINGS_2027_SOURCE,
    qsYear: 2027,
    qsWorld: 1001,
    qsWorldDisplay: "1001-1200",
    qsOverallScore: null,
    academicReputation: 14.4,
    citationsPerFaculty: 3.8,
  },
  diu: {
    verified: true,
    source: QS_RANKINGS_2027_SOURCE,
    qsSource: QS_RANKINGS_2027_SOURCE,
    qsYear: 2027,
    qsWorld: 1001,
    qsWorldDisplay: "1001-1200",
    qsOverallScore: null,
    academicReputation: 17,
    citationsPerFaculty: 9.4,
  },
  aiub: {
    verified: true,
    source: QS_RANKINGS_2027_SOURCE,
    qsSource: QS_RANKINGS_2027_SOURCE,
    qsYear: 2027,
    qsWorld: 1401,
    qsWorldDisplay: "1401+",
    qsOverallScore: null,
    academicReputation: 10.8,
    citationsPerFaculty: 4.5,
    qsStars: 4,
  },
  "bangladesh-agricultural-university": {
    verified: true,
    source: QS_RANKINGS_2027_SOURCE,
    qsSource: QS_RANKINGS_2027_SOURCE,
    qsYear: 2027,
    qsWorld: 1401,
    qsWorldDisplay: "1401+",
    qsOverallScore: null,
    academicReputation: 6.9,
    citationsPerFaculty: 16,
  },
  cuet: {
    verified: true,
    source: QS_RANKINGS_2027_SOURCE,
    qsSource: QS_RANKINGS_2027_SOURCE,
    qsYear: 2027,
    qsWorld: 1401,
    qsWorldDisplay: "1401+",
    qsOverallScore: null,
    academicReputation: 7.9,
    citationsPerFaculty: 14.7,
  },
  iut: {
    verified: true,
    source: QS_RANKINGS_2027_SOURCE,
    qsSource: QS_RANKINGS_2027_SOURCE,
    qsYear: 2027,
    qsWorld: 1401,
    qsWorldDisplay: "1401+",
    qsOverallScore: null,
    academicReputation: 4.7,
    citationsPerFaculty: 17.7,
  },
  "jahangirnagar-university": {
    verified: true,
    source: QS_RANKINGS_2027_SOURCE,
    qsSource: QS_RANKINGS_2027_SOURCE,
    qsYear: 2027,
    qsWorld: 1401,
    qsWorldDisplay: "1401+",
    qsOverallScore: null,
    academicReputation: 11.2,
    citationsPerFaculty: 7.5,
  },
  kuet: {
    verified: true,
    source: QS_RANKINGS_2027_SOURCE,
    qsSource: QS_RANKINGS_2027_SOURCE,
    qsYear: 2027,
    qsWorld: 1401,
    qsWorldDisplay: "1401+",
    qsOverallScore: null,
    academicReputation: 6.4,
    citationsPerFaculty: 16.3,
  },
  sust: {
    verified: true,
    source: QS_RANKINGS_2027_SOURCE,
    qsSource: QS_RANKINGS_2027_SOURCE,
    qsYear: 2027,
    qsWorld: 1401,
    qsWorldDisplay: "1401+",
    qsOverallScore: null,
    academicReputation: 8.6,
    citationsPerFaculty: 12.5,
  },
  "university-of-rajshahi": {
    verified: true,
    source: QS_RANKINGS_2027_SOURCE,
    qsSource: QS_RANKINGS_2027_SOURCE,
    qsYear: 2027,
    qsWorld: 1401,
    qsWorldDisplay: "1401+",
    qsOverallScore: null,
    academicReputation: 11.4,
    citationsPerFaculty: 7.1,
  },
};

export function getQsRankedBangladesh2027(): { slug: string; rankings: Partial<UniversityRanking> }[] {
  return Object.entries(QS_WORLD_RANKINGS_2027)
    .map(([slug, rankings]) => ({ slug, rankings }))
    .sort((a, b) => (a.rankings.qsWorld ?? 9999) - (b.rankings.qsWorld ?? 9999));
}
