export const courseData = [
  {
    code: "SE 224",
    title: "Database System Lab",
    credit: "1",
    section: "42B2",
    teacher: "Prof. Dr. A. H. M. Saifullah Sadi",
  },
  {
    code: "SE 223",
    title: "Database System",
    credit: "3",
    section: "42_B",
    teacher: "Prof. Dr. A. H. M. Saifullah Sadi",
  },
  {
    code: "SE 133",
    title: "Software Development Capstone Project",
    credit: "3",
    section: "43H2",
    teacher: "Ms. Sumona Afroz",
  },
  {
    code: "SE 132",
    title: "Data Structure Lab",
    credit: "1",
    section: "43H2",
    teacher: "Maliha Bushra Hoque",
  },
  {
    code: "SE 131",
    title: "Data Structure",
    credit: "3",
    section: "43H",
    teacher: "Maliha Bushra Hoque",
  },
  {
    code: "GE 235",
    title: "Principles of Accounting, Business & Economics",
    credit: "3",
    section: "41A",
    teacher: "Ms. Shahana Kabir",
  },
  {
    code: "SE 234",
    title: "Theory of Computing",
    credit: "3",
    section: "41_A",
    teacher: "Ms. Fatama Binta Rafiq",
  },
  {
    code: "SE 233",
    title: "Operating System & System Programming 1 Lab",
    credit: "1",
    section: "41_A1",
    teacher: "Ms. Ishrat Sultana",
  },
  {
    code: "SE 232",
    title: "Operating System & System Programming",
    credit: "3",
    section: "41A",
    teacher: "Ms. Ishrat Sultana",
  },
  {
    code: "SE 231",
    title: "System Analysis & Design Capstone Project",
    credit: "3",
    section: "41A1",
    teacher: "Tapushe Rabaya Toma",
  },
];
