import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { Roadmap, RoadmapNode, InterviewQuestion, CodingProblem } from "./types";
import { PDF_GITHUB, PDF_VERSION, PDF_PLATFORM, PDF_COMPANY, PDF_COMPANY_URL } from "./content/constants";

export type ExportSection =
  | "full"
  | "overview"
  | "topics"
  | "interview"
  | "coding"
  | "projects"
  | "resources"
  | "career"
  | "portfolio"
  | "readiness"
  | "certificate";

type ExportOptions = {
  studentName?: string;
  sections?: ExportSection[];
  node?: RoadmapNode | null;
};

const BRAND_RGB: [number, number, number] = [109, 93, 246];
const MARGIN = 20;
const PAGE_W = 210;
const PAGE_H = 297;
const CONTENT_W = PAGE_W - MARGIN * 2;

function addHeaderFooter(doc: jsPDF, roadmapTitle: string, chapter: string) {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    if (i === 1) continue;
    doc.setFontSize(8);
    doc.setTextColor(100);
    doc.text(PDF_PLATFORM, MARGIN, 12);
    doc.text(roadmapTitle, PAGE_W / 2, 12, { align: "center" });
    doc.text(chapter, PAGE_W - MARGIN, 12, { align: "right" });
    doc.setDrawColor(220);
    doc.line(MARGIN, 14, PAGE_W - MARGIN, 14);
    doc.text(`${PDF_PLATFORM} · ${PDF_COMPANY}`, MARGIN, PAGE_H - 10);
    doc.text(PDF_COMPANY_URL, MARGIN, PAGE_H - 6);
    doc.text(`Page ${i} of ${pageCount}`, PAGE_W - MARGIN, PAGE_H - 10, { align: "right" });
  }
}

function coverPage(doc: jsPDF, roadmap: Roadmap, studentName?: string) {
  doc.setFillColor(...BRAND_RGB);
  doc.rect(0, 0, PAGE_W, 90, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(28);
  doc.text(PDF_PLATFORM, PAGE_W / 2, 35, { align: "center" });
  doc.setFontSize(14);
  doc.text("Interactive Career Roadmap", PAGE_W / 2, 48, { align: "center" });
  doc.setTextColor(0);
  doc.setFontSize(22);
  doc.text(roadmap.title, PAGE_W / 2, 110, { align: "center" });
  doc.setFontSize(11);
  doc.setTextColor(80);
  const meta = [
    `Category: ${roadmap.category}`,
    `Difficulty: ${roadmap.difficulty}`,
    `Learning Time: ${roadmap.learningMonths} months · ${roadmap.learningHours} hours`,
    `Version: ${PDF_VERSION}`,
    `Generated: ${new Date().toLocaleDateString()}`,
  ];
  if (studentName) meta.push(`Student: ${studentName}`);
  meta.forEach((line, i) => doc.text(line, PAGE_W / 2, 130 + i * 8, { align: "center" }));
  doc.setFontSize(10);
  doc.text(`Generated by ${PDF_PLATFORM}`, PAGE_W / 2, 200, { align: "center" });
}

function brandingPage(doc: jsPDF) {
  doc.addPage();
  doc.setFontSize(16);
  doc.text(`Thank you for using ${PDF_PLATFORM}.`, PAGE_W / 2, 80, { align: "center" });
  doc.setFontSize(12);
  doc.text(`${PDF_PLATFORM} · A product of ${PDF_COMPANY}`, PAGE_W / 2, 100, { align: "center" });
  doc.text(PDF_COMPANY_URL, PAGE_W / 2, 112, { align: "center" });
  doc.text(PDF_GITHUB, PAGE_W / 2, 124, { align: "center" });
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`${PDF_VERSION} · ${new Date().toLocaleString()}`, PAGE_W / 2, 145, { align: "center" });
  doc.text(`Copyright © ${PDF_PLATFORM} · ${PDF_COMPANY}`, PAGE_W / 2, 158, { align: "center" });
}

function sectionTitle(doc: jsPDF, title: string, y: number): number {
  if (y > PAGE_H - 40) {
    doc.addPage();
    y = 24;
  }
  doc.setFontSize(14);
  doc.setTextColor(...BRAND_RGB);
  doc.text(title, MARGIN, y);
  doc.setDrawColor(...BRAND_RGB);
  doc.line(MARGIN, y + 2, PAGE_W - MARGIN, y + 2);
  doc.setTextColor(0);
  return y + 12;
}

function bodyText(doc: jsPDF, text: string, y: number, maxW = CONTENT_W): number {
  doc.setFontSize(10);
  const lines = doc.splitTextToSize(text, maxW);
  for (const line of lines) {
    if (y > PAGE_H - 30) {
      doc.addPage();
      y = 24;
    }
    doc.text(line, MARGIN, y);
    y += 5;
  }
  return y + 4;
}

function codeBlock(doc: jsPDF, code: string, y: number): number {
  doc.setFillColor(245, 245, 250);
  const lines = doc.splitTextToSize(code, CONTENT_W - 8);
  const h = lines.length * 4.5 + 8;
  if (y + h > PAGE_H - 30) {
    doc.addPage();
    y = 24;
  }
  doc.rect(MARGIN, y - 4, CONTENT_W, h, "F");
  doc.setFont("courier", "normal");
  doc.setFontSize(8);
  lines.forEach((line: string, i: number) => {
    doc.text(String(i + 1).padStart(2, " "), MARGIN + 2, y + 2 + i * 4.5);
    doc.text(line, MARGIN + 12, y + 2 + i * 4.5);
  });
  doc.setFont("helvetica", "normal");
  return y + h + 6;
}

export function exportRoadmapPdf(roadmap: Roadmap, options: ExportOptions = {}) {
  const sections = options.sections ?? ["full"];
  const include = (s: ExportSection) => sections.includes("full") || sections.includes(s);
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const filename = `${roadmap.slug}-bornoflow-roadmap.pdf`;

  coverPage(doc, roadmap, options.studentName);
  doc.addPage();
  let y = 24;

  if (include("overview")) {
    y = sectionTitle(doc, "Roadmap Overview", y);
    y = bodyText(doc, roadmap.description, y);
    y = bodyText(doc, `Prerequisites: ${roadmap.prerequisites.join("; ")}`, y);
  }

  if (include("topics") && !options.node) {
    y = sectionTitle(doc, "Learning Topics", y);
    autoTable(doc, {
      startY: y,
      head: [["Topic", "Difficulty", "Hours"]],
      body: roadmap.nodes.map((n) => [n.title, n.difficulty, String(n.estimatedHours)]),
      styles: { fontSize: 8 },
      headStyles: { fillColor: BRAND_RGB },
      margin: { left: MARGIN, right: MARGIN },
    });
    y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10;
  }

  if (options.node && include("topics")) {
    y = sectionTitle(doc, `Topic: ${options.node.title}`, y);
    y = bodyText(doc, options.node.description, y);
    if (options.node.theory) y = bodyText(doc, options.node.theory, y);
    if (options.node.codeExample) y = codeBlock(doc, options.node.codeExample, y);
  }

  if (include("interview")) {
    doc.addPage();
    y = 24;
    y = sectionTitle(doc, "Interview Preparation", y);
    const questions: InterviewQuestion[] = options.node
      ? options.node.interviewQuestions
      : roadmap.enrichment.interviewHub.slice(0, 30);
    questions.slice(0, 25).forEach((q, i) => {
      y = bodyText(doc, `${i + 1}. [${q.difficulty}/${q.category}] ${q.question}`, y);
      y = bodyText(doc, `Answer: ${q.answer}`, y);
    });
  }

  if (include("coding")) {
    doc.addPage();
    y = 24;
    y = sectionTitle(doc, "Coding Problems", y);
    const problems: CodingProblem[] = options.node
      ? options.node.codingProblems
      : roadmap.enrichment.codingProblems.slice(0, 20);
    problems.slice(0, 15).forEach((p, i) => {
      y = bodyText(doc, `${i + 1}. ${p.title} (${p.difficulty})`, y);
      y = bodyText(doc, p.statement, y);
      y = codeBlock(doc, p.solution, y);
      y = bodyText(doc, `Time: ${p.timeComplexity} · Space: ${p.spaceComplexity}`, y);
    });
  }

  if (include("career")) {
    doc.addPage();
    y = 24;
    const c = roadmap.enrichment.career;
    y = sectionTitle(doc, "Career & Salary Outlook", y);
    y = bodyText(doc, c.overview, y);
    autoTable(doc, {
      startY: y,
      head: [["Region", "Entry", "Mid", "Senior", "Lead"]],
      body: c.salaries.map((s) => [s.region, s.entry, s.mid, s.senior, s.lead]),
      styles: { fontSize: 7 },
      headStyles: { fillColor: BRAND_RGB },
      margin: { left: MARGIN, right: MARGIN },
    });
    y = bodyText(doc, c.salaryDisclaimer, (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8);
  }

  if (include("portfolio")) {
    doc.addPage();
    y = 24;
    y = sectionTitle(doc, "Portfolio Checklist", y);
    roadmap.enrichment.portfolioChecklist.forEach((item, i) => {
      y = bodyText(doc, `${i + 1}. [ ] ${item.label}`, y);
    });
  }

  addHeaderFooter(doc, roadmap.title, options.node?.title ?? "Complete Roadmap");
  brandingPage(doc);
  addHeaderFooter(doc, roadmap.title, "Closing");
  doc.save(filename);
}

export function exportRoadmapMarkdown(roadmap: Roadmap, node?: RoadmapNode | null): string {
  const lines: string[] = [
    `# ${roadmap.title} Roadmap`,
    "",
    roadmap.description,
    "",
    "## Topics",
    ...roadmap.nodes.map((n) => `- ${n.title} (${n.difficulty})`),
    "",
    "## Interview Questions (sample)",
    ...roadmap.enrichment.interviewHub.slice(0, 20).map((q) => `### ${q.question}\n${q.answer}`),
  ];
  if (node) {
    lines.push("", `## Topic: ${node.title}`, node.theory ?? "");
  }
  return lines.join("\n");
}

export function exportRoadmapJson(roadmap: Roadmap): string {
  return JSON.stringify(roadmap, null, 2);
}

export function exportRoadmapHtml(roadmap: Roadmap): string {
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${roadmap.title}</title>
<style>body{font-family:system-ui;max-width:800px;margin:40px auto;padding:0 20px}h1{color:#6D5DF6}code{background:#f4f4f8;padding:2px 6px;border-radius:4px}</style>
</head><body><h1>${roadmap.title}</h1><p>${roadmap.description}</p>
<h2>Topics</h2><ul>${roadmap.nodes.map((n) => `<li>${n.title}</li>`).join("")}</ul>
<p><small>${PDF_PLATFORM} · A product of ${PDF_COMPANY} · ${PDF_COMPANY_URL}</small></p></body></html>`;
}

export function printRoadmap() {
  if (typeof window !== "undefined") window.print();
}
