import type { CareerTool } from "./types";

export const CAREER_TOOLS: CareerTool[] = [
  {
    slug: "resume-builder",
    title: "Resume Builder",
    description: "25+ premium templates, ATS optimization, PDF/DOCX export, version history.",
    icon: "FileText",
    category: "resume",
    href: "/cv-builder",
    external: true,
    featured: true,
    popular: true,
  },
  {
    slug: "ats-checker",
    title: "ATS Resume Checker",
    description: "Score your resume, find missing keywords, and get actionable ATS suggestions.",
    icon: "ScanSearch",
    category: "resume",
    href: "/career/ats-checker",
    featured: true,
    popular: true,
  },
  {
    slug: "cover-letter",
    title: "Cover Letter Builder",
    description: "Internship, job, scholarship, and research letters with live preview.",
    icon: "Mail",
    category: "resume",
    href: "/career/cover-letter",
    popular: true,
  },
  {
    slug: "portfolio",
    title: "Portfolio Builder",
    description: "Modern developer portfolio with projects, skills, and GitHub integration.",
    icon: "Layout",
    category: "resume",
    href: "/career/portfolio",
    featured: true,
  },
  {
    slug: "linkedin",
    title: "LinkedIn Optimizer",
    description: "Analyze headline, about, skills, and get profile improvement suggestions.",
    icon: "Linkedin",
    category: "resume",
    href: "/career/linkedin",
    popular: true,
  },
  {
    slug: "github-readme",
    title: "GitHub README Generator",
    description: "Professional README with badges, stats, shields, and tech icons.",
    icon: "Github",
    category: "resume",
    href: "/career/github-readme",
  },
  {
    slug: "internship-tracker",
    title: "Internship Tracker",
    description: "Track applications, deadlines, interviews, and offers in one dashboard.",
    icon: "GraduationCap",
    category: "applications",
    href: "/career/internship-tracker",
    featured: true,
    popular: true,
  },
  {
    slug: "job-tracker",
    title: "Job Tracker",
    description: "Manage job applications, recruiters, salary notes, and interview pipeline.",
    icon: "Briefcase",
    category: "applications",
    href: "/career/job-tracker",
    popular: true,
  },
  {
    slug: "salary-calculator",
    title: "Salary Calculator",
    description: "Monthly, annual, hourly, tax estimation for BD, US, UK, and more.",
    icon: "DollarSign",
    category: "applications",
    href: "/career/salary-calculator",
    popular: true,
  },
  {
    slug: "interview",
    title: "Interview Prep Hub",
    description: "Technical, behavioral, and HR interview prep with MCQs and mock interviews.",
    icon: "MessageSquare",
    category: "interview",
    href: "/career/interview",
    featured: true,
    popular: true,
  },
  {
    slug: "mock-interview",
    title: "Mock Interview",
    description: "Timed interview simulator with scoring and performance analytics.",
    icon: "Video",
    category: "interview",
    href: "/career/interview/mock",
    popular: true,
  },
  {
    slug: "roadmaps",
    title: "Career Roadmaps",
    description: "Frontend, backend, DevOps, AI/ML, and 14 career paths with timelines.",
    icon: "Map",
    category: "growth",
    href: "/career/roadmaps",
    featured: true,
    popular: true,
  },
  {
    slug: "analytics",
    title: "Career Analytics",
    description: "Resume score, applications, interview readiness, and skill progress.",
    icon: "BarChart3",
    category: "analytics",
    href: "/career/analytics",
  },
];

export function getCareerTool(slug: string) {
  return CAREER_TOOLS.find((t) => t.slug === slug);
}
