"use client";

import { useState } from "react";
import Link from "next/link";
import { Home, ChevronRight, Search, RefreshCw } from "lucide-react";
import { Section, InfoCard, CodeBlock, Diagram, InterviewQuestion, AnimatedFlow } from "../components";

interface PageTableEntry {
  valid: boolean;
  frame: number;
  dirty: boolean;
  prot: string;
}

const DEFAULT_PT: PageTableEntry[] = Array.from({ length: 16 }, (_, i) => ({
  valid: i < 8,
  frame: i < 8 ? (i * 3 + 2) % 64 : 0,
  dirty: i % 3 === 0,
  prot: i < 8 ? "R/W" : "---",
}));

export default function VirtualMemoryPage() {
  const [virtualAddr, setVirtualAddr] = useState("");
  const [pageSize, setPageSize] = useState(4096);
  const [pageTable] = useState<PageTableEntry[]>(DEFAULT_PT);
  const [transResult, setTransResult] = useState<{ vpn: number; offset: number; pfn: number; physAddr: string; hit: boolean } | null>(null);
  const [tlbEnabled, setTlbEnabled] = useState(true);
  const [tlbHits, setTlbHits] = useState(0);
  const [tlbMisses, setTlbMisses] = useState(0);
  const [tlbCache, setTlbCache] = useState<{ vpn: number; pfn: number }[]>([]);

  const translateAddress = () => {
    const addr = parseInt(virtualAddr.trim().startsWith("0x") ? virtualAddr.trim() : "0x" + virtualAddr.trim(), 16);
    if (isNaN(addr) || addr < 0) return;

    const offsetBits = Math.ceil(Math.log2(pageSize));
    const offset = addr & ((1 << offsetBits) - 1);
    const vpn = addr >> offsetBits;
    const pte = pageTable[vpn % pageTable.length];

    let pfn: number;
    let hit: boolean;

    if (tlbEnabled) {
      const tlbEntry = tlbCache.find(t => t.vpn === vpn);
      if (tlbEntry) {
        pfn = tlbEntry.pfn;
        hit = true;
        setTlbHits(h => h + 1);
      } else if (pte.valid) {
        pfn = pte.frame;
        hit = false;
        setTlbMisses(m => m + 1);
        setTlbCache(t => [{ vpn, pfn }, ...t].slice(0, 8));
      } else {
        setTransResult({ vpn, offset, pfn: -1, physAddr: "PAGE FAULT", hit: false });
        return;
      }
    } else {
      if (pte.valid) {
        pfn = pte.frame;
        hit = true;
      } else {
        setTransResult({ vpn, offset, pfn: -1, physAddr: "PAGE FAULT", hit: false });
        return;
      }
    }

    const physAddr = (pfn << offsetBits) | offset;
    setTransResult({ vpn, offset, pfn, physAddr: `0x${physAddr.toString(16).toUpperCase()}`, hit });
  };

  return (
    <div className="max-w-5xl mx-auto px-6 py-8">
      <div className="flex items-center gap-2 mb-6 text-xs text-slate-500">
        <Link href="/tools/arch" className="text-cyan-600 no-underline flex items-center gap-1.5 hover:text-cyan-800 transition">
          <Home size={16} /> Architecture
        </Link>
        <ChevronRight size={16} />
        <span className="text-slate-900 font-semibold">Virtual Memory</span>
      </div>

      <div className="mb-10">
        <h1 className="text-4xl font-extrabold text-slate-900 mb-3">🔄 Virtual Memory</h1>
        <p className="text-base text-slate-500 leading-relaxed max-w-xl">
          Virtual memory gives each process its own address space, mapped to physical memory via page tables. It enables isolation, sharing, and programs larger than RAM.
        </p>
      </div>

      <Section title="Virtual vs Physical Address">
        <InfoCard title="Key Insight" type="info">
          Every memory address generated by a program is virtual. The MMU (Memory Management Unit) translates it to a physical address. The program sees a contiguous address space starting at 0, even if physical memory is fragmented.
        </InfoCard>

        <Diagram title="Address Translation Overview">
          <AnimatedFlow steps={[
            { label: "CPU", desc: "Virtual Address" },
            { label: "MMU", desc: "Translation" },
            { label: "TLB", desc: "Cache Lookup" },
            { label: "Page Table", desc: "Walk Tables" },
            { label: "Physical", desc: "Memory Access" },
          ]} />
        </Diagram>

        <div className="grid sm:grid-cols-2 gap-4">
          <div className="bg-cyan-50 border border-cyan-200 rounded-xl p-4">
            <h4 className="text-sm font-bold text-cyan-700 mb-2">Virtual Address</h4>
            <ul className="text-xs text-slate-600 space-y-1">
              <li>Generated by CPU/program</li>
              <li>Per-process address space (e.g., 4GB on 32-bit)</li>
              <li>Contiguous, starting from 0</li>
              <li>Isolated from other processes</li>
            </ul>
          </div>
          <div className="bg-amber-50 border border-amber-200 rounded-xl p-4">
            <h4 className="text-sm font-bold text-amber-700 mb-2">Physical Address</h4>
            <ul className="text-xs text-slate-600 space-y-1">
              <li>Actual RAM location</li>
              <li>Shared across all processes</li>
              <li>May be fragmented</li>
              <li>Managed by OS kernel</li>
            </ul>
          </div>
        </div>
      </Section>

      <Section title="Page Tables & TLB">
        <div className="grid sm:grid-cols-2 gap-4 mb-4">
          <div className="bg-white rounded-xl border border-slate-200 p-4">
            <h4 className="text-sm font-bold text-slate-900 mb-3">Page Table Entry (PTE)</h4>
            <div className="space-y-2">
              {[
                { field: "Frame Number", bits: "20 bits", desc: "Physical page frame address" },
                { field: "Valid Bit", bits: "1 bit", desc: "Is this mapping valid?" },
                { field: "Dirty Bit", bits: "1 bit", desc: "Has the page been written to?" },
                { field: "Reference Bit", bits: "1 bit", desc: "Has the page been accessed?" },
                { field: "Protection", bits: "2 bits", desc: "R/W/X permissions" },
              ].map((e, i) => (
                <div key={i} className="flex items-center gap-3 text-xs">
                  <span className="w-24 font-bold text-slate-700">{e.field}</span>
                  <span className="w-20 font-mono text-slate-400">{e.bits}</span>
                  <span className="text-slate-500">{e.desc}</span>
                </div>
              ))}
            </div>
          </div>
          <div className="bg-white rounded-xl border border-slate-200 p-4">
            <h4 className="text-sm font-bold text-slate-900 mb-3">TLB (Translation Lookaside Buffer)</h4>
            <InfoCard title="Fast Path" type="tip">
              TLB is a hardware cache for recent page table translations. With TLB hit (99%+), translation takes ~1 cycle. A miss requires walking the page table in memory (10-100 cycles).
            </InfoCard>
            <div className="flex items-center gap-2 mt-3">
              <label className="text-xs font-semibold text-slate-700">
                <input type="checkbox" checked={tlbEnabled} onChange={e => setTlbEnabled(e.target.checked)} className="mr-2 accent-cyan-600" />
                Enable TLB
              </label>
              <span className="text-xs text-slate-400">Hits: {tlbHits} · Misses: {tlbMisses}</span>
            </div>
            {tlbCache.length > 0 && (
              <div className="mt-2 flex flex-wrap gap-1">
                {tlbCache.map((t, i) => (
                  <span key={i} className="bg-cyan-100 text-cyan-700 text-[10px] font-mono px-2 py-0.5 rounded">
                    VPN 0x{t.vpn.toString(16)} → PFN 0x{t.pfn.toString(16)}
                  </span>
                ))}
              </div>
            )}
          </div>
        </div>
      </Section>

      <Section title="📱 Interactive: Virtual → Physical Translation">
        <InfoCard title="Try It" type="info">
          Enter a virtual address (hex) to see how the MMU translates it using the page table. Watch how TLB accelerates repeated translations.
        </InfoCard>

        <div className="bg-white rounded-xl border border-slate-200 p-5 mb-4">
          <div className="flex items-center gap-3 mb-4">
            <input type="text" value={virtualAddr} onChange={e => setVirtualAddr(e.target.value)}
              placeholder="Enter virtual address (e.g., 0x1A4F or 1A4F)" onKeyDown={e => e.key === "Enter" && translateAddress()}
              className="flex-1 p-2.5 border border-slate-200 rounded-lg text-sm font-mono" />
            <select value={pageSize} onChange={e => setPageSize(Number(e.target.value))}
              className="p-2.5 border border-slate-200 rounded-lg text-sm bg-white">
              <option value={4096}>4 KB pages</option>
              <option value={8192}>8 KB pages</option>
              <option value={65536}>64 KB pages</option>
            </select>
            <button onClick={translateAddress}
              className="bg-cyan-600 text-white px-5 py-2.5 rounded-lg font-semibold text-sm hover:bg-cyan-700 transition flex items-center gap-2">
              <Search size={16} /> Translate
            </button>
            <button onClick={() => { setTlbCache([]); setTlbHits(0); setTlbMisses(0); setTransResult(null); }}
              className="bg-slate-100 text-slate-600 px-4 py-2.5 rounded-lg text-sm hover:bg-slate-200 transition flex items-center gap-2">
              <RefreshCw size={16} />
            </button>
          </div>

          {transResult && (
            <div className={`${transResult.physAddr === "PAGE FAULT" ? "bg-pink-50 border-pink-300" : "bg-emerald-50 border-emerald-300"} border rounded-xl p-4`}>
              <div className="flex items-center gap-3 mb-3">
                <span className={`font-bold text-base ${transResult.physAddr === "PAGE FAULT" ? "text-pink-700" : "text-emerald-700"}`}>
                  {transResult.physAddr === "PAGE FAULT" ? "⚠️ PAGE FAULT" : transResult.hit ? "✅ TLB Hit" : "⚡ TLB Miss → Page Table Walk"}
                </span>
              </div>
              <div className="grid sm:grid-cols-4 gap-3 text-xs">
                <div className="bg-white rounded-lg p-3 border border-slate-100">
                  <span className="block font-bold text-slate-400 mb-1">Virtual Address</span>
                  <span className="font-mono text-slate-900">0x{((transResult.vpn << Math.ceil(Math.log2(pageSize))) | transResult.offset).toString(16).toUpperCase()}</span>
                </div>
                <div className="bg-white rounded-lg p-3 border border-slate-100">
                  <span className="block font-bold text-slate-400 mb-1">VPN (Page #)</span>
                  <span className="font-mono text-slate-900">0x{transResult.vpn.toString(16).toUpperCase()}</span>
                </div>
                <div className="bg-white rounded-lg p-3 border border-slate-100">
                  <span className="block font-bold text-slate-400 mb-1">Offset</span>
                  <span className="font-mono text-slate-900">0x{transResult.offset.toString(16).toUpperCase()}</span>
                </div>
                {transResult.physAddr !== "PAGE FAULT" && (
                  <div className="bg-cyan-50 rounded-lg p-3 border border-cyan-200">
                    <span className="block font-bold text-cyan-600 mb-1">Physical Address</span>
                    <span className="font-mono text-cyan-800">{transResult.physAddr}</span>
                  </div>
                )}
              </div>
            </div>
          )}
        </div>
      </Section>

      <Section title="Page Fault Handling">
        <div className="bg-white rounded-xl border border-slate-200 p-4 mb-4">
          <div className="flex flex-col gap-2">
            {[
              { step: "1", desc: "MMU checks TLB and page table — valid bit = 0", color: "bg-red-100 text-red-700" },
              { step: "2", desc: "Hardware traps to OS kernel (page fault exception)", color: "bg-orange-100 text-orange-700" },
              { step: "3", desc: "OS checks if the address is valid (part of process address space)", color: "bg-amber-100 text-amber-700" },
              { step: "4", desc: "If valid: OS finds a free page frame (or evicts one using replacement algorithm)", color: "bg-yellow-100 text-yellow-700" },
              { step: "5", desc: "OS initiates disk I/O to load the page from swap/disk into the frame", color: "bg-lime-100 text-lime-700" },
              { step: "6", desc: "Page table updated with valid bit = 1 and frame number", color: "bg-emerald-100 text-emerald-700" },
              { step: "7", desc: "CPU restarts the instruction that caused the fault", color: "bg-cyan-100 text-cyan-700" },
            ].map((s, i) => (
              <div key={i} className="flex items-center gap-3">
                <span className={`${s.color} w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold shrink-0`}>{s.step}</span>
                <p className="text-xs text-slate-600">{s.desc}</p>
              </div>
            ))}
          </div>
        </div>
        <InfoCard title="Demand Paging" type="tip">
          Pages are loaded only when needed (on demand), not upfront. This saves memory and startup time. The first access to a page always causes a page fault.
        </InfoCard>
      </Section>

      <Section title="Code Example: Address Translation">
        <CodeBlock code={`class MMU:
    def __init__(self, page_size=4096):
        self.page_size = page_size
        self.page_table = {}  # VPN -> PFN mapping
        self.tlb = {}  # VPN -> PFN cache
        self.tlb_size = 16

    def translate(self, virtual_addr):
        vpn = virtual_addr // self.page_size
        offset = virtual_addr % self.page_size

        # TLB check (fast path)
        if vpn in self.tlb:
            pfn = self.tlb[vpn]
            return (pfn * self.page_size) + offset, True  # TLB hit

        # Page table walk (slow path)
        if vpn in self.page_table:
            pfn = self.page_table[vpn]
            # Update TLB
            if len(self.tlb) >= self.tlb_size:
                self.tlb.pop(next(iter(self.tlb)))
            self.tlb[vpn] = pfn
            return (pfn * self.page_size) + offset, False  # TLB miss

        raise PageFault(f"VPN {vpn} not in memory")`} language="python" />
      </Section>

      <Section title="Interview Questions">
        <div className="space-y-3">
          <InterviewQuestion question="What is the difference between virtual and physical address?" answer="A virtual address is generated by the CPU during program execution — each process has its own virtual address space starting at 0. The physical address is the actual location in RAM hardware. The MMU translates virtual to physical. Virtual memory allows processes to use more memory than physically available, provides isolation, and eliminates fragmentation." />
          <InterviewQuestion question="How does TLB improve performance?" answer="TLB (Translation Lookaside Buffer) is a hardware cache of recent VPN→PFN translations. Without TLB, every memory access requires a page table walk (multiple memory accesses). TLB hit rate is typically 99%+, reducing translation from ~50 cycles to ~1 cycle. The TLB exploits both temporal locality (same page accessed repeatedly) and spatial locality (nearby pages)." />
          <InterviewQuestion question="What happens during a page fault?" answer="When the accessed page's valid bit is 0: the MMU triggers a page fault exception, the OS traps in, checks validity, finds/evicts a page frame, initiates disk I/O to load the page, updates the page table, and restarts the faulting instruction. Page faults are expensive (~10ms for disk I/O = millions of cycles)." />
          <InterviewQuestion question="Explain demand paging." answer="Demand paging loads pages only when they are accessed, not at program startup. When a program starts, no pages are in memory. The first access to each instruction/data page triggers a page fault, and the OS loads just that page. This reduces memory usage and startup time, and allows programs larger than physical RAM to run." />
        </div>
      </Section>
    </div>
  );
}
